spring:
  profiles:
    active:
    - dev
---
spring:
  profiles: dev
  application:
    name: deptProvider
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
          url: jdbc:mysql://127.0.0.1:3306/clouddb2?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
          username: root
          password: root
          driverClassName: com.mysql.cj.jdbc.Driver #mysql8驱动类
          type: com.alibaba.druid.pool.DruidDataSource #使用druid连接池
          druid:
              initial-size: 8 #初始连接池数
              min-idle: 3 #最小连接池数量
              max-active: 20
              max-wait: 50000
server:
  port: 5050
  servlet:
    context-path: /provider
  tomcat:
    uri-encoding: UTF-8

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
eureka:
  instance:
    instance-id: deptProvider:127.0.0.1:5050 #实例ID
    prefer-ip-address: true #展示IP
  client:
    service-url: #Eureka集群注册连接
      #defaultZone: http://localhost.com:10102/eureka
      defaultZone: http://eureka7071.com:7071/eureka,http://eureka7072.com:7072/eureka

info:
  app.name: deptProvider
  author.name: sunming
  build.artifactId: provider
  build.version: 0.0.1-SNAPSHOT
